name: true_root
description: Supply chain traceability for agricultural products
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  http: ^1.2.1
  mobile_scanner: ^5.2.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#007E6E"
  adaptive_icon_foreground: assets/icon/app_icon.png

flutter_native_splash:
  color: "#007E6E"
  image: assets/icon/app_icon.png
  android: true
  ios: false
  android_12:
    color: "#007E6E"
    image: assets/icon/app_icon.png
